/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    openFb
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xtase_hardware_TFTScreen_openFb
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Test
 * Method:    closeFb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xtase_hardware_TFTScreen_closeFb
  (JNIEnv *, jobject);

  
JNIEXPORT void JNICALL Java_com_xtase_hardware_TFTScreen_resetFrame
  (JNIEnv *env, jobject, jint index);  


 // uses 320x240 caches
JNIEXPORT void JNICALL Java_com_xtase_hardware_TFTScreen_fill
  (JNIEnv *, jobject, jintArray, jint index, jint x, jint y, jint w, jint h);
  
 // do not use caches
JNIEXPORT void JNICALL Java_com_xtase_hardware_TFTScreen_fillDirect
  (JNIEnv *, jobject, jintArray, jint x, jint y, jint w, jint h);

JNIEXPORT void JNICALL Java_com_xtase_hardware_TFTScreen_fillColor
  (JNIEnv *, jobject, jint color, jint x, jint y, jint w, jint h);



/*
 * Class:     Test
 * Method:    drawString
 * Signature: ([IILjava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_com_xtase_hardware_TFTScreen_drawString
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint zoom, jboolean renderSapces);


JNIEXPORT void JNICALL Java_com_xtase_hardware_TFTScreen_blitPixel
  (JNIEnv *env, jobject, jint x, jint y, jint color);

JNIEXPORT void JNICALL Java_com_xtase_hardware_TFTScreen_FX_1starField
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif